- name: Setup package management variables
  tags:
    - always
  block:
    - name: Include Debian variables
      ansible.builtin.include_vars:
        file: debian.yml
        name: pkgs
      when: ansible_facts['distribution'] == "Debian"
