- name: Install desktop apps
  tags:
    - desktop
    - applications
  block:
    - name: Install desktop apps
      become: true
      ansible.builtin.package:
        name: "{{ pkgs.desktop_apps }}"
        state: present
    - name: Install flatpaks
      community.general.flatpak:
        name:
          - com.spotify.Client
          - com.discordapp.Discord
          - com.github.tchx84.Flatseal
          - org.onlyoffice.desktopeditors
        state: present
