- name: Install awesomewm
  tags:
    - desktop
    - awesome
  block:
    - name: Install awesome
      become: true
      ansible.builtin.dnf:
        name:
          - awesome
          - dunst
          - kitty
          - alacritty
          - picom
          - rofi
          - flameshot
          - xrandr
        state: present
