- name: Install awesomewm
  tags:
    - desktop
    - awesome
  block:
    - name: Install awesome
      become: true
      ansible.builtin.package:
        name: "{{ pkgs.awesome + pkgs.x_wm_common }}"
        state: present
    - include: ../lib/dotfiles.yml
      vars:
        directories:
          - awesome
          - rofi
          - kitty
          - picom
          - dunst
