- name: Install bspwm
  tags:
    - desktop
    - bspwm
  block:
    - name: Install bspwm
      become: true
      ansible.builtin.package:
        name: "{{ pkgs.bspwm }}"
        state: present
    - include: ../lib/dotfiles.yml
      vars:
        directories:
          - bspwm
          - rofi
          - kitty
          - picom
          - dunst
