- name: Setup cli tools
  tags:
    - cli
    - cli-tools
  block:
    - name: Create SourcePackages directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/SourcePackages"
        state: directory
    - name: Clone delta
      ansible.builtin.git:
        repo: https://github.com/dandavison/delta
        dest: "{{ lookup('env', 'HOME') }}/SourcePackages/delta"
    - name: Build delta
      shell:
        cmd: cargo build --release
        chdir: "{{ lookup('env', 'HOME') }}/SourcePackages/delta"
    - name: Download lazygit
      ansible.builtin.get_url:
        checksum: sha256:a992717f728a9a64eb744816dbb0fe0e277205451b94662213a79cb2b08f3fd3
        url: https://github.com/jesseduffield/lazygit/releases/download/v0.38.2/lazygit_0.38.2_Linux_x86_64.tar.gz
        dest: /tmp/lazygit.tar.gz
    - name: Install lazygit
      become: true
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/lazygit.tar.gz
        dest: "{{ lookup('env', 'HOME') }}/.local/bin"
    - name: Install CLI-Tools
      become: true
      ansible.builtin.package:
        name: "{{ pkgs.cli_tools }}"
        state: present
    - name: Clone findproject
      ansible.builtin.git:
        repo: https://github.com/m-gail/findproject
        dest: "{{ lookup('env', 'HOME') }}/SourcePackages/findproject"
    - name: Build findproject
      shell:
        cmd: "python3 -m zipapp findproject -p '/usr/bin/env python3' -o $HOME/.local/bin/findproject"
        chdir: "{{ lookup('env', 'HOME') }}/SourcePackages/findproject"
    - name: Link fp_tmux
      file:
        src: "{{ lookup('env', 'HOME') }}/SourcePackages/findproject/scripts/fp_tmux"
        dest: "{{ lookup('env', 'HOME') }}/.local/bin/fp_tmux"
        state: link
    - include: ../lib/dotfiles.yml
      vars:
        directories:
          - findproject
