- name: Install dotfiles
  tags:
    - cli
    - desktop
    - dotfiles
  block:
    - name: Install stow
      become: true
      ansible.builtin.package:
        name: "{{ pkgs.stow }}"
        state: present
    - name: Clone dotfiles
      ansible.builtin.git:
        repo: https://github.com/m-gail/dotfiles
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    - name: Stow dotfiles
      shell: cd $HOME/.dotfiles && stow */
