- name: Install dotfiles
  tags:
    - cli
    - dotfiles
  block:
    - name: Install stow
      become: true
      ansible.builtin.dnf:
        name: stow
        state: present
    - name: Clone dotfiles
      ansible.builtin.git:
        repo: https://gitlab.com/ihciM/dotfiles
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    - name: Stow dotfiles
      shell: cd $HOME/.dotfiles && stow */
