- name: Install eww
  tags:
    - desktop
    - eww
  block:
    - name: Install eww dependencies
      become: true
      ansible.builtin.package:
        name: "{{ pkgs.eww }}"
        state: present
    - name: Create SourcePackages directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/SourcePackages"
        state: directory
    - name: Clone eww
      ansible.builtin.git:
        repo: https://github.com/elkowar/eww
        dest: "{{ lookup('env', 'HOME') }}/SourcePackages/eww"
    - name: Build eww
      shell:
        cmd: cargo build --release --no-default-features --features x11
        chdir: "{{ lookup('env', 'HOME') }}/SourcePackages/eww"
    - name: Make eww executable
      file:
        dest: "{{ lookup('env', 'HOME') }}/SourcePackages/eww/target/release/eww"
        mode: +x
    - name: Link to local bin
      file:
        src: "{{ lookup('env', 'HOME') }}/SourcePackages/eww/target/release/eww"
        dest: "{{ lookup('env', 'HOME') }}/.local/bin/eww"
        state: link
