- name: Install greetd
  tags:
    - greetd
  block:
    - name: Install greetd
      become: true
      ansible.builtin.package:
        name: "{{ pkgs.greetd }}"
        state: present
    - name: Enable greetd systemd
      become: true
      ansible.builtin.systemd:
        name: greetd
        enabled: yes
        force: true
