- name: Setup javascript
  tags:
    - cli
    - dev
    - javascript
  block:
    - name: Clone nvm
      ansible.builtin.git:
        repo: https://github.com/nvm-sh/nvm
        dest: "{{ lookup('env', 'HOME') }}/.nvm"
