- name: Install lightdm
  tags:
    - desktop
    - lightdm
  block:
    - name: Install lightdm
      become: true
      ansible.builtin.dnf:
        name:
          - lightdm
          - light-locker
          - slick-greeter
          - "@base-x"
        state: present
    - name: Enable lightdm
      become: true
      ansible.builtin.systemd:
        name: lightdm
        enabled: yes
        force: true
    - name: Change default target to graphical.target
      become: yes
      file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link
