- name: Setup neovim
  tags:
    - cli
    - neovim
  block:
    - name: Enable Copr for neovim nightly
      become: true
      community.general.copr:
        name: agriffis/neovim-nightly
      when: ansible_facts['distribution'] == "Fedora"
    - name: Install neovim and plugin dependencies
      become: true
      ansible.builtin.package:
        name: "{{ pkgs.neovim }}"
        state: present
    - name: Create .local/bin on debian
      file:
        path: "{{ lookup('env', 'HOME') }}/.local/bin"
        state: directory
        recurse: true
    - name: Install v0.9.4 AppImage on Debian
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/download/v0.9.4/nvim.appimage
        checksum: sha256:028cfaaf551d64cbb2f39d15363ed78edb01e2673579b48cb694e3604207d656
        dest: "{{ lookup('env', 'HOME') }}/.local/bin/nvim"
        mode: "u+x"
    - name: Install nightly AppImage on Debian
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
        dest: "{{ lookup('env', 'HOME') }}/.local/bin/nvim_nightly"
        mode: "u+x"
      when: ansible_facts['distribution'] == "Debian"
    - name: Create SourcePackages directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/SourcePackages"
        state: directory
    - name: Clone vscode-java-test
      ansible.builtin.git:
        repo: https://github.com/microsoft/vscode-java-test
        dest: "{{ lookup('env', 'HOME') }}/SourcePackages/vscode-java-test"
    - name: Install jdk version
      shell:
        cmd: source $HOME/.sdkman/bin/sdkman-init.sh && yes n | sdk install java 17.0.7-tem
      args:
        executable: /bin/bash
    - name: Install vscode-java-test
      shell:
        cmd: source $HOME/.sdkman/bin/sdkman-init.sh && sdk use java 17.0.7-tem && cd $HOME/SourcePackages/vscode-java-test && npm install && npm run build-plugin
      args:
        executable: /bin/bash
    - name: Clone java-debug
      ansible.builtin.git:
        repo: https://github.com/microsoft/java-debug
        dest: "{{ lookup('env', 'HOME') }}/SourcePackages/java-debug"
    - name: Install java-debug
      shell:
        cmd: source $HOME/.sdkman/bin/sdkman-init.sh && sdk use java 17.0.7-tem && cd $HOME/SourcePackages/java-debug && ./mvnw clean install
      args:
        executable: /bin/bash
    - include: ../lib/dotfiles.yml
      vars:
        directories:
          - vim
