- name: Install sway
  tags:
    - desktop
    - sway
  block:
    - name: Install sway
      become: true
      ansible.builtin.package:
        name: "{{ pkgs.sway }}"
        state: present
    - include: ../lib/dotfiles.yml
      vars:
        directories:
          - sway
          - kitty
          - dunst
