- name: Setup tmux
  tags:
    - cli
    - tmux
  block:
    - name: Install tmux
      become: true
      ansible.builtin.package:
        name: "{{ pkgs.tmux }}"
        state: present
    - include: ../lib/dotfiles.yml
      vars:
        directories:
          - tmux
