- name: Install wallpapers
  tags:
    - desktop
    - wallpapers
  block:
    - name: Create Wallpaper directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/Pictures/Wallpapers"
        state: directory
    - name: Download wallpaper
      ansible.builtin.get_url:
        url: "https://images.pexels.com/photos/971360/pexels-photo-971360.jpeg?cs=srgb&dl=pexels-creative-free-stock-971360.jpg&fm=jpg"
        dest: "{{ lookup('env', 'HOME') }}/Pictures/Wallpapers/pexels-creative-free-stock-971360.jpg"
    - name: Download rofi wallpaper
      ansible.builtin.get_url:
        url: "https://images.pexels.com/photos/1381679/pexels-photo-1381679.jpeg?cs=srgb&dl=pexels-irina-iriser-971360.jpg&fm=jpg"
        dest: "{{ lookup('env', 'HOME') }}/Pictures/Wallpapers/pexels-irina-iriser-971360.jpg"
    - name: Download rofi wallpaper scaled
      ansible.builtin.get_url:
        url: "https://images.pexels.com/photos/1381679/pexels-photo-1381679.jpeg?cs=srgb&dl=pexels-irina-iriser-971360-scaled.jpg&fm=jpg&w=1280&h=1920"
        dest: "{{ lookup('env', 'HOME') }}/Pictures/Wallpapers/pexels-irina-iriser-971360-scaled.jpg"
