- name: Setup zsh
  vars:
    the_user: "{{ ansible_user_id }}"
  tags:
    - cli
    - zsh
  block:
    - name: Download starship
      become: true
      ansible.builtin.get_url:
        checksum: sha256:bb797f4af36138581cb43d36f432d54312360da21dff4c38545675c7873758ae
        url: https://github.com/starship/starship/releases/download/v1.16.0/starship-x86_64-unknown-linux-gnu.tar.gz
        dest: /tmp/starship.tar.gz
    - name: Install starship
      become: true
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/starship.tar.gz
        dest: "{{ lookup('env', 'HOME') }}/.local/bin"
    - name: Install zsh and config dependencies
      become: true
      ansible.builtin.package:
        name: "{{ pkgs.zsh }}"
        state: present
    - name: Install syntax highlighting
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: "{{ lookup('env', 'HOME') }}/.config/zsh/plugins/zsh-syntax-highlighting"
    - name: Install autosuggestions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "{{ lookup('env', 'HOME') }}/.config/zsh/plugins/zsh-autosuggestions"
    - name: Change shell to zsh
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh
    - include: ../lib/dotfiles.yml
      vars:
        directories:
          - zsh
